apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hearth.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hearth.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels: {{- include "hearth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "hearth.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hearth.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: {{ include "hearth.operatorImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect={{ .Values.operator.leaderElect }}
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0
            - --gateway-image={{ include "hearth.gatewayImage" . }}
            - --gateway-replicas={{ .Values.gateway.replicas }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources: {{- toYaml .Values.operator.resources | nindent 12 }}
