apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hearth
    app.kubernetes.io/managed-by: kustomize
  name: llmservice-editor-role
rules:
- apiGroups:
  - serving.hearth.dev
  resources:
  - llmservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.hearth.dev
  resources:
  - llmservices/status
  verbs:
  - get
