apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Intentionally empty. Apply one device profile from a vendor subdirectory.
resources: []

# +kubebuilder:scaffold:manifestskustomizesamples
