resources:
- bases/serving.hearth.dev_inferenceruntimes.yaml
- bases/serving.hearth.dev_llmservices.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# +kubebuilder:scaffold:crdkustomizewebhookpatch

#configurations:
#- kustomizeconfig.yaml
